### ISSUE TITLE
float button border radius can not control 

### ISSUE THREAD

**Issue by shalinasanga** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#13]
After installing Version 2018.1.5 (Not updated PCL, but update work on droid and ios, separate issue added) **in droid project** previously worked floating button with, width and height 50 and border radius 30 looks like tiny flat egg. No icon in there.
My button has no BackgroundColor, if i add background color, it is looking big with tiny ellipse inside it, still no icon.
Remove border radius and border radius 20 both seems not working

**Comment by SuavePirate** [comment]
Can you attach screenshots? You shouldn't be using the border radius property when using this control since the shape is managed by the native renderer.

**Comment by shalinasanga** [comment]
i am using  PCL profile 259 and in  android main activity ` new FloatingActionButtonRenderer();` and `Forms.SetFlags("FastRenderers_Experimental");` codes use.
Below button codes working fine in this environment under 2017.10.17 version of this button control.
` BorderRadius="30" WidthRequest="50" HeightRequest="50"   
Image="plus_icon.png" ButtonColor="Green"`

After update to version 2018.1.5 (nuget Update only work on android and ios proj, **PCL not updated**) of this control this happens

**Comment by SuavePirate** [comment]
You should either migrate from 259 to 111 or implement it in your project using the source code here since we won't support 259 moving forward. Also, don't set the Border Radius of the control. This is already handled in the renderer and changing it can mess with the containing layout. Also make sure it's containing layout has the proper width and height to contain it and that it isn't trying to fill the container. The best way to check is to switch the FAB for a regular button. If your regular button is not a perfect square, the FAB won't be a perfect circle.

**Comment by SuavePirate** [comment]
Also, your border radius needs to be the 1/2 the width and height, or you'll get an egg shape - it's how all radii work. So if you're using Width and Height of 50, your BorderRadius should be 25.
