### ISSUE TITLE
Floating Popup Menu

### ISSUE THREAD

**Issue by npagare** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#25]
Hi @SuavePirate,

Thank you for helping us with this great renderer.

Any thought on supporting a ListView on the ButtonClick event that opens up a dynamic floating menu [served via an ItemTemplate + dynamic data template containing floating menu (image, and label) ]  on the appropriate side on the screen depending on the button's position ?

Thanks,

**Comment by SuavePirate** [comment]
I don't plan on implementing that in this control, since it isn't part of the native Android FAB, but perhaps as an extension. Waiting to see how Xamarin.Forms implements the built-in one: https://github.com/xamarin/Xamarin.Forms/pull/3295

It's not too difficult to do yourself now. Bind the icon to something dynamic, and have the click handler of the main fab show a hidden list of smaller fabs above it. Could work easily with Xamarin.Forms animations too.

**Comment by npagare** [comment]
Hi @SuavePirate , the XF builtin FAB is not coming out for next couple months may be late '18 or early '19. It is part of vNext+1. They are barely getting 3.2 out (pre2). 

I would still urge you to release the final version of your beta version. May developers will love it and will be benefited from your delivery.

Thanks for your other suggestion. Will look into it.

Thanks

**Comment by rasmuschristensen** [comment]
@IoTFier you might get some inspiration from this one https://winstongubantes.blogspot.com/2018/01/transform-floating-action-button-into.html
